<div id="content">
<div class="grid-item"></div>
<div class="grid-item column">
    <div class="perex"><span>02</span>Meet your crew</div>
    <div class="rank">Commander</div>
    <h2>Douglas Hurley</h2>
    <p>Douglas Gerald Hurley is an American engineer, former Marine Corps pilot and former NASA astronaut. He launched into space for the third time as commander of Crew Dragon Demo-2.</p>

        <ul class="bullets">
            <li id="crew0" class="active"></li>
            <li id="crew1"></li>
            <li id="crew2"></li>
            <li id="crew3"></li>
        </ul>
</div>   
<div class="grid-item image">
    <img src="img/crew/image-douglas-hurley.png" alt="" class="portrait">
</div>
<div class="grid-item"></div>
</div>
