<div id="content">
<div class="grid-item"></div>
<div class="grid-item column"><div class="perex"><span>01</span>Pick your destinaton</div>
        <img class="planet" data-target="mars" src="img/destination/image-mars.png" alt="">
    </div>
        <div class="grid-item"></div>
<div class="grid-item">
    <ul id="destination-nav">
        <li id="moon">Moon</li>
        <li id="mars" class="active">Mars</li>
        <li id="europa">Europa</li>
        <li id="titan">Titan</li>
</ul>
<div class="info" data-target="mars">
<h1>Mars</h1>
<p>Don’t forget to pack your hiking boots. You’ll need them to tackle Olympus Mons, the tallest planetary mountain in our solar system. It’s two and a half times the size of Everest!</p>
<div class="flex">
    <div class="item"><span>Avg. Distance</span><div id="distance" class="value">225 Mil. Km</div></div>
    <div class="item"><span>Est. Travel Time</span><div id="time" class="value">9 Months</div></div>
</div>
</div>



<div class="info hidden" data-target="titan">
<h1>Titan</h1>
<p>Don’t forget to pack your hiking boots. You’ll need them to tackle Olympus Mons, the tallest planetary mountain in our solar system. It’s two and a half times the size of Everest!</p>
<div class="flex">
    <div class="item"><span>Avg. Distance</span><div class="value">225 Mil. Km</div></div>
    <div class="item"><span>Est. Travel Time</span><div class="value">9 Months</div></div>
</div>
</div>
</div>
<div class="grid-item"></div>
</div>
