<div id="content">
<div class="grid-item"></div>
<div class="grid-item text"><div class="perex">So, you want to travel to</div>
        <h1>Space</h1>
        <p>Let’s face it; if you want to go to space, you might as well genuinely go to 
  outer space and not hover kind of on the edge of it. Well sit back, and relax 
  because we’ll give you a truly out of this world experience!</p></div>
<div class="grid-item explore"><div class="circle"><h2>Explore</h2></div></div>
<div class="grid-item"></div>
</div>

