<div id="kontakty" class="container-fluid paddingTB80">
    <div class="container">
        <div class="left">
            <h3>Soukromá podřipská střední odborná škola
                a střední odborné učiliště o. p. s.</h3>
            <p><span><i class="fa fa-map-marker"></i></span><?php echo $options[1][0] ?></p>
            <p><span><i class="fa fa-envelope-o"></i></span><?php echo $options[12][0] ?></p>
            <p><span><i class="fa fa-mouse-pointer"></i></span>www.podripskaskola.cz</p>
            <p><span><i class="fa"></i></span>www.re-kvalifikace.cz</p>
            <a class="button" href=""><span><i class="fa fa-map-marker"></i></span>Ukázat na mapě</a>
            <div class="data">
                <p><span><strong>Datová schránka:</strong></span><span class="right"><?php echo $options[3][0] ?></span></p>
                <p><span><strong>IZO:</strong></span><span class="right"><?php echo $options[4][0] ?></span></p>
                <p><span><strong>REDIZO:</strong></span><span class="right"><?php echo $options[5][0] ?></span></p>
            </div>
        </div>
        <div class="right">
            <h3>Pobočka Ústí nad Labem<br>
                <p></p></h3>
            <p><span><i class="fa fa-map-marker"></i></span><?php echo $options[11][0] ?></p>
            <p><span><i class="fa fa-mobile-phone"></i></span><?php echo $options[2][0] ?></p>
            <p><span><i class="fa fa-envelope-o"></i></span>+420 416 839 064</p>
            <p><span><i class="fa fa-mouse-pointer"></i></span>www.maturitnistudium.cz</p>
            <a class="button" href=""><span><i class="fa fa-map-marker"></i></span>Ukázat na mapě</a>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="container">
        <div class="left">
            <h3>Telefonní kontakty</h3>
            <div class="contacts-phone">
                <p>Ředitelna<span class="right"><?php echo $options[6][0] ?></span></p>
                <p>Kancelář<span class="right"><?php echo $options[7][0] ?></span></p>
                <p>Sborovna<span class="right"><?php echo $options[8][0] ?></span></p>
                <p>UOV - kadeřnictví<span class="right"><?php echo $options[9][0] ?></span></p>
                <p>UOV - restaurace<span class="right"><?php echo $options[10][0] ?></span></p>
            </div>
            <a class="button kontakty" href="#"><span class="fa fa-user"></span>Kontakty na vyučující a další pracovníky
                školy</a>
            <p class="rejstrik">Společnost je zapsána v rejstříku obecně prospěšných společností Krajského soudu
                v Ústí nad Labem oddíl 0, vložka 35.</p>
            <div class="bank">
                <p><span><strong>IČO:</strong></span><span class="right"><?php echo $options[14][0] ?></span></p>
                <p><span><strong>číslo účtu:</strong></span><span class="right"><?php echo $options[15][0] ?></span></p>
                <p><span><strong>bankovní spojení:</strong></span><span class="right"><?php echo $options[16][0] ?></span>
                </p>
            </div>
        </div>
        <div class="right">
            <h3>Novinky z první ruky</h3>
            <p>Cokoliv se u nás šustne to sdílíme, přihlaš se, ať už ti nic neunikne.</p>
            <p class="socials"><a href=""><i class="fa fa-instagram"></i></a>|<a href=""><i
                            class="fa fa-facebook-f"></i></a></p>
        </div>
    </div>
    <div id="obor-contact" class="container paddingTB40">
        <h3>Napište nám</h3>
        <form class="form-horizontal" id="contact-form">
            <fieldset>
                <!-- Text input-->
                <div class="form-group">
                    <div class="col-md-4">
                        <div class="input-ux">
                            <i class="fa fa-check"></i>
                            <i class="fa fa-times"></i>
                            <input id="name" name="name" type="text" placeholder="Jméno a příjmení" class="validation input"
                                   data-type="text">
                            <div class="help">Toto pole je povinné!</div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="input-ux">
                            <i class="fa fa-check"></i>
                            <i class="fa fa-times"></i>
                            <input id="email" name="email" type="email" placeholder="Email"
                                   class="validation input" data-type="email">
                            <div class="help">Email není ve správném tvaru!</div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="input-ux">
                            <i class="fa fa-check"></i>
                            <i class="fa fa-times"></i>
                            <input id="phone" name="phone" type="tel" placeholder="Telefon"
                                   class="validation input" data-type="tel">
                            <div class="help">Telefon není ve správném tvaru!</div>
                        </div>
                    </div>
                </div>

                <!-- Textarea -->
                <div class="form-group">
                    <div class="col-md-12">
                        <textarea class="form-control" id="textarea" name="message" rows="6"
                                  placeholder="Dotaz"></textarea>
                    </div>
                </div>
                <div class="col-md-12 paddingLR0">
                    <a id="send-form" class="button">Odeslat zprávu <span><i class="fa fa-paper-plane"></i></span></a>
                </div>

            </fieldset>
        </form>
        <!--        <form id="contact-form" class="form-horizontal">-->
        <!--            <div class="form-group">-->
        <!--                <div class="col-md-4">-->
        <!--                    <div class="input-ux">-->
        <!--                        <i class="fa fa-check"></i>-->
        <!--                        <i class="fa fa-times"></i>-->
        <!--                    <input class="validation input" type="text" name="name" placeholder="Jméno a příjmení">-->
        <!--                    </div>-->
        <!--                </div>-->
        <!--                <div class="col-md-4">-->
        <!--                    <input type="email" name="email" placeholder="Email" class="validation">-->
        <!--                </div>-->
        <!--                <div class="col-md-4">-->
        <!--                    <input type="text" name="phone" placeholder="Telefon">-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            <div class="form-group">-->
        <!--                <div class="col-md-12">-->
        <!--                    <textarea name="zprava" placeholder="Dotaz" rows="6"></textarea>-->
        <!--                </div>-->
        <!--                <div class="col-md-12">-->
        <!--                    <a id="send-form" class="button">Odeslat zprávu <span><i class="fa fa-paper-plane"></i></span></a>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--        </form>-->
    </div>
</div>
<?php print_r($content['options']);

