<div class="perex"><span>03</span>Space launch 101</div>
<div id="content">
<div class="grid-item"></div>
<div class="grid-item">
    <div class="group circles">
        <div id="tech0" class="circle active">1</div>
        <div id="tech1" class="circle">2</div>
        <div id="tech2" class="circle">3</div>
    </div>
    <div class="group">
        <div class="perex">
The technology...
        </div>

        <h1>
            Launch vehicle
        </h1>
        <p>A launch vehicle or carrier rocket is a rocket-propelled vehicle used to carry a payload from Earth's surface to space, usually to Earth orbit or beyond. Our WEB-X carrier rocket is the most powerful in operation. Standing 150 metres tall, it's quite an awe-inspiring sight on the launch pad!</p>
    </div>
        
</div>   
<div class="grid-item image">
    <img src="../img/technology/image-launch-vehicle-portrait.jpg" alt="">
</div>
</div>
